# Generated by Django 5.1.5 on 2025-02-28 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('courses', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='student')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_num', models.CharField(max_length=50)),
                ('house_name', models.TextField(max_length=500)),
                ('post_office', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('ALAPPUZHA', 'Alappuzha'), ('ERNAKULAM', 'Ernakulam'), ('IDUKKI', 'Idukki'), ('KANNUR', 'Kannur'), ('KASARAGOD', 'Kasaragod'), ('KOLLAM', 'Kollam'), ('KOTTAYAM', 'Kottayam'), ('KOZHIKODE', 'Kozhikode'), ('MALAPPURAM', 'Malappuram'), ('PALAKKAD', 'Palakkad'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('THRISSUR', 'Thrissur'), ('WAYANAD', 'Wayanad')], max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('adm_number', models.CharField(max_length=50)),
                ('Join_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batches')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainers')),
            ],
            options={
                'verbose_name': 'students',
                'verbose_name_plural': 'students',
                'ordering': ['id'],
            },
        ),
    ]
