# Generated by Django 5.1.5 on 2025-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
