# Generated by Django 5.1.5 on 2025-02-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.baseclass')),
                ('name', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='courses')),
                ('duration', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('offer_fee', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
            },
            bases=('student.baseclass',),
        ),
    ]
