# Generated by Django 5.1.5 on 2025-02-28 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('employee_id', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='trainers')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('house_name', models.CharField(max_length=25)),
                ('post_office', models.CharField(max_length=25)),
                ('district', models.CharField(choices=[('ALAPPUZHA', 'Alappuzha'), ('ERNAKULAM', 'Ernakulam'), ('IDUKKI', 'Idukki'), ('KANNUR', 'Kannur'), ('KASARAGOD', 'Kasaragod'), ('KOLLAM', 'Kollam'), ('KOTTAYAM', 'Kottayam'), ('KOZHIKODE', 'Kozhikode'), ('MALAPPURAM', 'Malappuram'), ('PALAKKAD', 'Palakkad'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('THRISSUR', 'Thrissur'), ('WAYANAD', 'Wayanad')], max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('qualification', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=25)),
                ('id_card', models.FileField(upload_to='trainers/idproof')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainers',
                'verbose_name_plural': 'Trainers',
            },
        ),
    ]
