# Generated by Django 5.1.5 on 2025-02-28 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_councellors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('expecting_end_date', models.DateField()),
                ('offline_capacity', models.IntegerField()),
                ('online_capacity', models.IntegerField()),
                ('batch_ended', models.BooleanField(default=False)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('academic_counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_councellors.academiccounsellors')),
            ],
            options={
                'verbose_name': 'Batches',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
