# Generated by Django 5.1.5 on 2025-02-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.baseclass')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('expecting_end_date', models.DateField()),
                ('offline_capacity', models.IntegerField()),
                ('online_capacity', models.IntegerField()),
                ('batch_ended', models.BooleanField(default=False)),
                ('ended_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batches',
                'verbose_name_plural': 'Batches',
            },
            bases=('student.baseclass',),
        ),
    ]
